apiVersion: v1
kind: Service
metadata:
  name: promexporter
  namespace: default
spec:
        #type: NodePort
  selector:
    app: exporter
  ports:
    - name: prometheus
      protocol: TCP
      port: 9113
      targetPort: 9113
